version: "3"
services:
    unifi-controller:
        image: linuxserver/unifi-controller
        container_name: unifi-controller
        environment:
            - PUID=1000
            - GUID=1000
            - MEM_LIMIT=1024M
        volumes:
            - unifi_controller_data:/config
        ports:
            - 3478:3478/udp
            - 10001:10001/udp
            - 8080:8080
            - 8081:8081
            - 8443:8443
            - 8843:8843
            - 8880:8880
            - 6789:6789
        restart: unless-stopped


