version: "3.7"

services:
  unifi-controller:
    image: linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - "./unifi/config:/config"
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    restart: unless-stopped
    #    labels:
    #      - "traefik.enable=true"
    #      - "traefik.http.routers.unifi.entrypoints=websecure"
    #      - "traefik.http.routers.unifi.rule=Host(`unifi.$MY_DOMAIN`)"
    #      - "traefik.http.routers.unifi.tls.certresolver=lets-encr"

    #networks:
    #  default:
    #    external:
    #      name: $DEFAULT_NETWORK
